### ISSUE TITLE
notice issue

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/nivo-slider-lite#21]
When I click on try notice I get this https://www.dropbox.com/s/hofkwg19ni160pv/Screenshot%202018-11-20%2016.28.04.png?dl=0, I think is better to redirect it at least to something like this : https://www.dropbox.com/s/mkzalnj411ei0lg/Screenshot%202018-11-20%2016.29.30.png?dl=0

**Comment by ineagu** [comment]
cc @selul

**Comment by selul** [comment]
@ineagu this is due to poopy site, it adds a padding top too which breaks that iframe. is not happening to users, if you test on wpsandbox or any other site it will show fine.

**Comment by ineagu** [comment]
Not the white space was the main problem, from the opened iframe users can’t install the plugin easily it seems to me
